### ISSUE TITLE
How i can use this with my React Js Website ?

### ISSUE THREAD

**Issue by ali-sultan-khan** [cometchat-pro-samples/javascript-reactjs-chat-app#2]

**Comment by mayur-bhandari** [comment]
Hello @ali-sultan-khan, this is a sample app for reactJs which consumes the CometChat Js SDK. You can use this project as reference to implement CometChat in your React Js Website. You can check the test folder present in the root directory.

**Comment by mayur-bhandari** [comment]
Closed due to inactivity.
