### ISSUE TITLE
Trying to use the demo but keeps showing CORS error

### ISSUE THREAD

**Issue by freenetbrasil** [cometchat-pro-samples/javascript-reactjs-chat-app#3]
Hi, downloaded the demo and provided the credentials, after running:

npm install
npm run dev

The server now listens on port 5000

So far, so good. When I access the site it shows up fine but when trying to login, I keep getting:

POST https://api.cometchat.com/v1.8/users/superhero1/auth_tokens 500
localhost/:1 Access to fetch at 'https://api.cometchat.com/v1.8/users/superhero1/auth_tokens' from origin 'http://localhost:5000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any ideas?

**Comment by ranjanravi85** [comment]
Hello @freenetbrasil,

Please try to run on https://localhost:5000, and you will not get that error, let us know if that solves your issue.

**Comment by freenetbrasil** [comment]
No luck, it seems it's not listening on https on port 5000, just http.

**Comment by ranjanravi85** [comment]
Try running following command for https:-

npm run sdev
